### ISSUE TITLE
Unable to use gem with Vite (without propshaft/sprockets)

### ISSUE THREAD

**Issue by jhliberty** [akodkod/solid-queue-dashboard#12]
I use vite-ruby to handle my assets in my rails app. When I add this gem and try to start the rails server i got the following error

```ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-8.0.0.beta1/lib/rails/railtie/configuration.rb:109:in `method_missing': undefined method `assets' for an instance of Rails::Application::Configuration (NoMethodError)
ruby/3.3.0/lib/ruby/gems/3.3.0/gems/solid_queue_dashboard-0.2.0/lib/solid_queue_dashboard/engine.rb:6:in `block in <class:Engine>'```

The issue is here: https://github.com/akodkod/solid-queue-dashboard/blob/51d25916a5533524299c6f911b6f0791babc3786/lib/solid_queue_dashboard/engine.rb#L6

**Comment by jhliberty** [comment]
Looks like the common pattern for handling this is wrapping with `if app.config.responds_to?(:assets)` and if not, skipping it and for vite users they can alias their gems and include any specific assets they need from the gem.
