### ISSUE TITLE
undefined method `job_status_circle_class' for an instance of

### ISSUE THREAD

**Issue by tripplesteel** [akodkod/solid-queue-dashboard#5]
I decided to try out the gem but when i try to enter the dashboard i get this error:

undefined method `job_status_circle_class' for an instance of #<Class:0x00007f770a223e80>

```
10:47:58 web.1  |
10:47:58 web.1  |
10:47:58 web.1  |
10:47:58 web.1  | ActionView::Template::Error (undefined method `job_status_circle_class' for an instance of #<Class:0x00007f770a223e80>):
10:47:58 web.1  |
10:47:58 web.1  | Causes:
10:47:58 web.1  | NoMethodError (undefined method `job_status_circle_class' for an instance of #<Class:0x00007f770a223e80>)
10:47:58 web.1  |     18:       <div class="card-content pt-5">
10:47:58 web.1  |     19:         <h4 class="font-medium">
10:47:58 web.1  |     20:           <%= status.to_s.titleize %>
10:47:58 web.1  |     21:           <span class="ml-0.5 -translate-y-px circle <%= job_status_circle_class(status) %>"></span>
10:47:58 web.1  |     22:         </h4>
10:47:58 web.1  |     23:         <p class="text-4xl font-bold mt-1 text-black dark:text-white">
10:47:58 web.1  |     24:           <%= number_with_delimiter(@jobs.with_status(status).count) %>
10:47:58 web.1  |
10:47:58 web.1  | solid_queue_dashboard (0.2.0) app/views/solid_queue_dashboard/dashboard/index.html.erb:21
10:47:58 web.1  | solid_queue_dashboard (0.2.0) app/views/solid_queue_dashboard/dashboard/index.html.erb:16:in `each'
10:47:58 web.1  | solid_queue_dashboard (0.2.0) app/views/solid_queue_dashboard/dashboard/index.html.erb:16
10:47:58 web.1  | actionview (7.2.1) lib/action_view/base.rb:281:in `public_send'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/base.rb:281:in `_run'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/template.rb:275:in `block in render'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications.rb:212:in `instrument'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/template.rb:574:in `instrument_render_template'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/template.rb:263:in `render'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:66:in `block (2 levels) in render_template'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications.rb:210:in `block in instrument'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications.rb:210:in `instrument'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications.rb:210:in `block in instrument'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications.rb:210:in `instrument'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:11:in `render'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/renderer.rb:58:in `render_template_to_object'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/renderer/renderer.rb:31:in `render_to_object'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/rendering.rb:135:in `block in _render_template'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/base.rb:308:in `in_rendering_context'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/rendering.rb:134:in `_render_template'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/streaming.rb:258:in `_render_template'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/rendering.rb:121:in `render_to_body'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/rendering.rb:186:in `render_to_body'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
10:47:58 web.1  | actionpack (7.2.1) lib/abstract_controller/rendering.rb:29:in `render'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/rendering.rb:167:in `render'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block (2 levels) in render'
10:47:58 web.1  | /home/blago/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/benchmark.rb:313:in `realtime'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in render'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:101:in `cleanup_view_runtime'
10:47:58 web.1  | activerecord (7.2.1) lib/active_record/railties/controller_runtime.rb:46:in `cleanup_view_runtime'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:31:in `render'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/implicit_render.rb:39:in `default_render'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/basic_implicit_render.rb:9:in `send_action'
10:47:58 web.1  | actionpack (7.2.1) lib/abstract_controller/base.rb:226:in `process_action'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/rendering.rb:193:in `process_action'
10:47:58 web.1  | actionpack (7.2.1) lib/abstract_controller/callbacks.rb:261:in `block in process_action'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
10:47:58 web.1  | turbo-rails (2.0.10) lib/turbo-rails.rb:24:in `with_request_id'
10:47:58 web.1  | turbo-rails (2.0.10) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
10:47:58 web.1  | audited (5.7.0) lib/audited/sweeper.rb:16:in `around'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
10:47:58 web.1  | audited (5.7.0) lib/audited/sweeper.rb:16:in `around'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
10:47:58 web.1  | actiontext (7.2.1) lib/action_text/rendering.rb:25:in `with_renderer'
10:47:58 web.1  | actiontext (7.2.1) lib/action_text/engine.rb:71:in `block (4 levels) in <class:Engine>'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `instance_exec'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:141:in `run_callbacks'
10:47:58 web.1  | actionpack (7.2.1) lib/abstract_controller/callbacks.rb:260:in `process_action'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/rescue.rb:27:in `process_action'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications.rb:210:in `block in instrument'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/notifications.rb:210:in `instrument'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:76:in `process_action'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
10:47:58 web.1  | activerecord (7.2.1) lib/active_record/railties/controller_runtime.rb:39:in `process_action'
10:47:58 web.1  | actionpack (7.2.1) lib/abstract_controller/base.rb:163:in `process'
10:47:58 web.1  | actionview (7.2.1) lib/action_view/rendering.rb:40:in `process'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal.rb:252:in `dispatch'
10:47:58 web.1  | actionpack (7.2.1) lib/action_controller/metal.rb:335:in `dispatch'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:67:in `dispatch'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:50:in `serve'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:53:in `block in serve'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `each'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `find_routes'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:34:in `serve'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:896:in `call'
10:47:58 web.1  | railties (7.2.1) lib/rails/engine.rb:535:in `call'
10:47:58 web.1  | railties (7.2.1) lib/rails/railtie.rb:226:in `public_send'
10:47:58 web.1  | railties (7.2.1) lib/rails/railtie.rb:226:in `method_missing'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/routing/mapper.rb:33:in `block in <class:Constraints>'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/routing/mapper.rb:62:in `serve'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:53:in `block in serve'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `each'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `find_routes'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/journey/router.rb:34:in `serve'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:896:in `call'
10:47:58 web.1  | rack-attack (6.7.0) lib/rack/attack.rb:103:in `call'
10:47:58 web.1  | rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
10:47:58 web.1  | warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
10:47:58 web.1  | warden (1.2.9) lib/warden/manager.rb:34:in `catch'
10:47:58 web.1  | warden (1.2.9) lib/warden/manager.rb:34:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/tempfile_reaper.rb:15:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/etag.rb:27:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/conditional_get.rb:27:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/head.rb:12:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context'
10:47:58 web.1  | rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/cookies.rb:704:in `call'
10:47:58 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:674:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/callbacks.rb:30:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/executor.rb:16:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
10:47:58 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
10:47:58 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
10:47:58 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
10:47:58 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
10:47:58 web.1  | railties (7.2.1) lib/rails/rack/logger.rb:41:in `call_app'
10:47:58 web.1  | railties (7.2.1) lib/rails/rack/logger.rb:29:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/request_id.rb:33:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/method_override.rb:24:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/runtime.rb:22:in `call'
10:47:58 web.1  | activesupport (7.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/executor.rb:16:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/static.rb:27:in `call'
10:47:58 web.1  | rack (2.2.9) lib/rack/sendfile.rb:110:in `call'
10:47:58 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
10:47:58 web.1  | rack-mini-profiler (3.3.1) lib/mini_profiler.rb:334:in `call'
10:47:58 web.1  | railties (7.2.1) lib/rails/engine.rb:535:in `call'
10:47:58 web.1  | puma (6.4.3) lib/puma/configuration.rb:272:in `call'
10:47:58 web.1  | puma (6.4.3) lib/puma/request.rb:100:in `block in handle_request'
10:47:58 web.1  | puma (6.4.3) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
10:47:58 web.1  | puma (6.4.3) lib/puma/request.rb:99:in `handle_request'
10:47:58 web.1  | puma (6.4.3) lib/puma/server.rb:464:in `process_client'
10:47:58 web.1  | puma (6.4.3) lib/puma/server.rb:245:in `block in run'
10:47:58 web.1  | puma (6.4.3) lib/puma/thread_pool.rb:155:in `block in spawn_thread

```

**Comment by akodkod** [comment]
@tripplesteel, thank you for your feedback. It looks like the helpers aren’t loading correctly. Could you provide a bit more information about your app? Is it API-only? Also, could you share your `Gemfile` with me?

**Comment by tripplesteel** [comment]
@akodkod Yes of cource. Its not API only. The app is new, running ruby 3.3.5 and rails 7.2.1. It's still in development phase, because of migration from old rails 4 app. Here you are the Gemfile

```
source 'https://rubygems.org'

ruby '3.3.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '= 7.2.1'
gem "pg"
# Use Puma as the app server
gem 'puma'
gem 'kamal'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"
gem 'sassc-rails'

# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"

gem 'haml'
gem 'haml-rails'
gem 'htmlentities'
gem 'nokogiri'

gem "bootsnap", require: false

gem 'devise'
gem 'httpclient'
gem 'rails-i18n'
gem 'multi_json'
gem 'lru_redux'
gem 'rack-attack'
gem 'net-sftp'
gem 'http-cookie'
gem 'sitemap_generator'
gem 'audited'
gem 'scenic'
gem 'dotenv'
gem "image_processing"
gem "solid_queue"
gem "solid_queue_dashboard"

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler'
  gem 'listen'
  gem 'rainbow'
  gem 'terminal-table'
  gem 'brakeman'
  gem 'foreman'
end
```

**Comment by thisIsLoading** [comment]
getting the same error now.

it was working earlier tho but i updated my rails app, maybe solid_queue did an update and that method is gone now
